// Generated by CoffeeScript 1.10.0
(function() {
  var api, platform;

  platform = require('os').platform();

  api = (function() {
    switch (platform) {
      case 'win32':
        return require('./api-win32');
      case 'darwin':
        return require('./api-darwin');
      case 'linux':
        return require('./api-linux');
      default:
        return function() {
          return callback(null, {});
        };
    }
  })();

  module.exports = {
    collect: api.collect
  };

}).call(this);
